# Generated by Django 3.2.8 on 2021-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='version',
            field=models.CharField(default='v0', max_length=5),
            preserve_default=False,
        ),
    ]
