# Generated by Django 3.2.8 on 2021-10-25 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_applog_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
