# Generated by Django 3.2.8 on 2021-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_applog_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
